[[outputs.influxdb]]
  urls = ["https://influxdb.service.consul:8086"]
  database = "telegraf"
  precision = "s"

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  fielddrop = ["time_*"]

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs"]

[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]

[[inputs.statsd]]
  service_address = ":8125"
