[meta]
  dir = "/mnt/persist/influx/meta"

[data]
  dir = "/mnt/persist/influx/data"
  wal-dir = "/mnt/persist/influx/wal"

[admin]
  https-enabled = true
  https-certificate = "/etc/influx.d/ssl/influx.crt"

[http]
  https-enabled = true
  https-certificate = "/etc/influx.d/ssl/influx.crt"
